export const KEY_PAGE = {
  SET_INTERNET: 'SET_INTERNET',
  SET_METAMASK_INFO: 'SET_METAMASK_INFO',
  SET_BALANCE: 'SET_BALANCE',
  SET_BNB_PRICE: 'SET_BNB_PRICE',
  CONNECTION_METHOD: 'CONNECTION_METHOD',
  SET_OPEN_MODAL: 'SET_OPEN_MODAL',
  MODAL_GLOBAL: 'MODAL_GLOBAL',
  SET_SIGN: 'SET_SIGN',
  SET_LOCALE: 'SET_LOCALE',
  META_MASK: 'META_MASK'
}
